main: main.cpp
	g++ -I./ -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_THREAD_SAFE -D_REENTRANT -o 'main' 'main.cpp' './DataStruct.cpp' './Drawer.cpp' './Trainer.cpp' ./lib/libfltk.a -lXrender -lXfixes -lXext -lpthread -ldl -lm -lX11
